#Workshop0
**Aditi Paudel**
**2408635**

##To - Do Task

###4.1 Exercise on Functions:

Task - 1:

Create a Python program that converts between different units of measurement.

In [ ]:
def convert_units():
    """
    Converts between length, weight, and volume units.

    Returns:
        float: converted value
    """
    try:
        print("Select conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter choice (1/2/3): ")

        value = float(input("Enter value to convert: "))

        if choice == "1":
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            c = input("Choose option: ")

            if c == "1":
                result = value * 3.28084
                print("Result:", result, "ft")

            elif c == "2":
                result = value / 3.28084
                print("Result:", result, "m")

        elif choice == "2":
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            c = input("Choose option: ")

            if c == "1":
                result = value * 2.20462
                print("Result:", result, "lbs")

            elif c == "2":
                result = value / 2.20462
                print("Result:", result, "kg")

        elif choice == "3":
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            c = input("Choose option: ")

            if c == "1":
                result = value * 0.264172
                print("Result:", result, "gal")

            elif c == "2":
                result = value / 0.264172
                print("Result:", result, "L")

        else:
            print("Invalid option")

    except ValueError:
        print("Invalid input. Please enter numeric value.")

convert_units()

Select conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 2
Enter value to convert: 5.6
1. Kilograms to Pounds
2. Pounds to Kilograms
Choose option: 2
Result: 2.5401202928395823 kg


###Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def find_sum(numbers):
    """Returns sum of numbers"""
    return sum(numbers)

def find_average(numbers):
    """Returns average of numbers"""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns maximum number"""
    return max(numbers)

def find_min(numbers):
    """Returns minimum number"""
    return min(numbers)

try:
    nums = input("Enter numbers separated by space: ")
    numbers = list(map(float, nums.split()))

    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter choice: ")

    if choice == "1":
        print("Sum =", find_sum(numbers))

    elif choice == "2":
        print("Average =", find_average(numbers))

    elif choice == "3":
        print("Max =", find_max(numbers))

    elif choice == "4":
        print("Min =", find_min(numbers))

    else:
        print("Invalid choice")

except:
    print("Invalid input")

Enter numbers separated by space: 3 456 66
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 1
Sum = 525.0


##4.2 Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


###2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))


[3, 4, 5]


###3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


###4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))


[2, 3, 4]


###5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


###6. Get Last n Elements

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


###7. Reverse Skip

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


#**Nested Lists**

###Exercise 4.3.1 – Flatten Nested List

In [ ]:
def flatten(lst):
    result = []
    for sub in lst:
        for item in sub:
            result.append(item)
    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


###Exercise 4.3.2 – Access Nested Element


In [ ]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


###Exercise 4.3.3 – Sum Nested List

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


###Exercise 4.3.4 – Remove Element from Nested List

In [ ]:
def remove_element(lst, elem):
    result = []
    for sub in lst:
        result.append([x for x in sub if x != elem])
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


###Exercise 4.3.5 – Find Maximum in Nested List

In [ ]:
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item,list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val,item)
    return max_val

print(find_max([[1,2],[3,[4,5]],6]))

6


###Exercise 4.3.6 – Count Occurrences

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item,list):
            count += count_occurrences(item,elem)
        else:
            if item == elem:
                count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


###Exercise 4.3.7 – Deep Flatten

In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


###Exercise 4.3.8 – Nested List Average

In [ ]:
def flatten(lst):
    result=[]
    for item in lst:
        if isinstance(item,list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

def average_nested(lst):
    flat = flatten(lst)
    return sum(flat)/len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


#**To Do NUMPY**

##10.1 Basic Vector and Matrix Operation with Numpy.

##Problem - 1: Array Creation:

1. Initialize an empty array with size 2×2

In [2]:
import numpy as np

arr = np.empty((2,2))
print(arr)

[[3.01103283e-315 0.00000000e+000]
 [5.90408447e-321 1.76262290e-312]]


2. Initialize an all-ones array with size 4×2

In [ ]:
arr = np.ones((4,2))
print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return an array filled with a specific value

In [ ]:
arr = np.full((3,3), 7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Create zeros array with same shape and type

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

zeros_arr = np.zeros_like(a)
print(zeros_arr)

[[0 0 0]
 [0 0 0]]


5. Create ones array with same shape and type

In [ ]:
ones_arr = np.ones_like(a)
print(ones_arr)

[[1 1 1]
 [1 1 1]]


6. Convert list to NumPy array

In [ ]:
new_list = [1,2,3,4]

arr = np.array(new_list)
print(arr)

[1 2 3 4]


##Problem 2: Array Manipulation

1. Array values from 10 to 49

In [ ]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create 3×3 matrix from 0–8

In [3]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3×3 identity matrix

In [4]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Random array size 30 and find mean

In [5]:
arr = np.random.random(30)

print(arr.mean())

0.41512910653498303


5. 10×10 random array → find min and max

In [6]:
arr = np.random.random((10,10))

print("Minimum:", arr.min())
print("Maximum:", arr.max())

Minimum: 0.010525615899703022
Maximum: 0.99180880367984


6. Replace 5th element with 1

In [7]:
arr = np.zeros(10)

arr[4] = 1

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array

In [8]:
arr = np.array([1,2,0,0,4,0])

reverse = arr[::-1]

print(reverse)

[0 4 0 0 2 1]


8. 2D array with border = 1 and inside = 0

In [9]:
arr = np.ones((5,5))

arr[1:-1,1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. 8×8 Checkerboard pattern

In [10]:
arr = np.zeros((8,8), dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem 3: Array Operations

In [11]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

1. Add arrays

In [12]:
print(x + y)

[[ 6  8]
 [10 13]]


2. Subtract arrays

In [13]:
print(x - y)

[[-4 -4]
 [-4 -3]]


3. Multiply with integer

In [14]:
print(x * 3)

[[ 3  6]
 [ 9 15]]


4. Square each element

In [15]:
print(x ** 2)

[[ 1  4]
 [ 9 25]]


5. Dot products

v and w

In [17]:
print(np.dot(v, w))

219


x and v

In [18]:
print(np.dot(x, v))

[29 77]


x and y

In [19]:
print(np.dot(x, y))

[[19 22]
 [50 58]]


###6. Concatenate arrays

x and y along rows

In [20]:
print(np.concatenate((x,y), axis=0))
print(np.vstack((x,y)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]


v and w along column

In [21]:
print(np.vstack((v,w)).T)

[[ 9 11]
 [10 12]]


###7. Concatenate x and v

In [22]:
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Dimensions are incompatible, so NumPy raises a dimension mismatch error.

##Problem 4: Matrix Operations

In [23]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

1. Prove A·A⁻¹ = I

In [24]:
A_inv = np.linalg.inv(A)

I = np.dot(A, A_inv)

print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ≠ BA

In [25]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB =")
print(AB)

print("BA =")
print(BA)

AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]


3. Prove (AB)ᵀ = BᵀAᵀ

In [26]:
left = np.transpose(np.dot(A,B))

right = np.dot(np.transpose(B), np.transpose(A))

print(left)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


##Solve Linear Equations

Step 1: Create matrices

In [27]:
A = np.array([
[2,-3,1],
[1,-1,2],
[3,1,-1]
])

B = np.array([-1,-3,9])

Step 2: Solve using inverse

In [28]:
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print(X)

[ 2.  1. -2.]


##1. Element-wise Addition

Python lists

In [29]:
import time

size = 1000000

a = list(range(size))
b = list(range(size))

start = time.time()

c = [a[i] + b[i] for i in range(size)]

end = time.time()

print("Python list addition time:", end-start)

Python list addition time: 0.11232566833496094


NumPy arrays

In [30]:
import numpy as np
import time

a = np.arange(size)
b = np.arange(size)

start = time.time()

c = a + b

end = time.time()

print("NumPy addition time:", end-start)

NumPy addition time: 0.019786357879638672


2. Element-wise Multiplication

Python lists

In [ ]:
start = time.time()

c = [a[i] * b[i] for i in range(size)]

end = time.time()

print("Python multiplication:", end-start)

NumPy

In [31]:
start = time.time()

c = a * b

end = time.time()

print("NumPy multiplication:", end-start)

NumPy multiplication: 0.004762411117553711


3. Dot Product

Python list

In [ ]:
start = time.time()

dot = sum(a[i] * b[i] for i in range(size))

end = time.time()

print("Python dot product:", end-start)

NumPy

In [32]:
start = time.time()

dot = np.dot(a,b)

end = time.time()

print("NumPy dot product:", end-start)

NumPy dot product: 0.0029439926147460938


4. Matrix Multiplication

Python lists

In [34]:
import random

size = 1000

A = [[random.random() for _ in range(size)] for _ in range(size)]
B = [[random.random() for _ in range(size)] for _ in range(size)]

start = time.time()

result = [[sum(A[i][k]*B[k][j] for k in range(size)) for j in range(size)] for i in range(size)]

end = time.time()

print("Python matrix multiplication:", end-start)

Python matrix multiplication: 179.5324683189392


NumPy

In [ ]:
A = np.random.rand(1000,1000)
B = np.random.rand(1000,1000)

start = time.time()

C = np.dot(A,B)

end = time.time()

print("NumPy matrix multiplication:", end-start)